dist: trusty
sudo: required

language: node_js
node_js:
  - "6.1"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm
  - npm install -g angular-cli
  - npm install -g karma
  - npm install

after_success:
  - npm run build
  - npm run test

notifications:
  email:
    - adrien.deperetti.freelance@gmail.com